Update gitlab-ci.yml

diff --git a/gitlab/simple/linux/gitlab-ci.yml b/gitlab/simple/linux/gitlab-ci.yml
--- a/gitlab/simple/linux/gitlab-ci.yml
+++ b/gitlab/simple/linux/gitlab-ci.yml
@@ -3,68 +3,30 @@
 #
 stages:
   - Scan
-variables:
-   # Endor Labs Configuration
-   #
-   ENDORCTL_VERSION: "latest" # Set to latest to download the latest version automatically otherwise, use a specific version of endorctl
-   ENDOR_NAMESPACE: "demo" # Insert your Endor Labs namespace here
-   DEBUG: "false"  ## Set DEBUG to "true" to send logs to Endor Labs support
-   ## If you would like to pin a specific version of endorctl to this job, you can implement an integrity check of the binary using the below variable.
-   # ENDORCTL_SHA: "Insert SHA256 hash for an integrity check here"
-   #
-   ## Scan scoping section
-   #
-   ## Use the following environment variables for custom paths, inclusions and exclusions.
-   # ENDOR_SCAN_PATH: "Insert a custom path to your git repository. Defaults to your pwd"
-   # ENDOR_SCAN_EXCLUDE: "Insert a regexp style pattern of paths to exclude in the scan. Generally used for monorepos."
-   # ENDORCTL_SCAN_INCLUDE: "Insert a regexp style pattern of paths to include in the scan. Generally used for monorepos."
-   #
-   ## Authentication to Endor Labs
-   #
-   ## Use the following environment variables for keyless authentication with your cloud provider. For more information visit: https://docs.api.endorlabs.com/continuous-integration/keyless-authentication/
-   #
-   # ENDOR_GCP_CREDENTIALS_SERVICE_ACCOUNT: "endorlabs@<yourproject.iam.gserviceaccount.com" 
-   # ENDOR_AWS_CREDENTIALS_ROLE_ARN: "arn:aws:iam::123456789012:role/my-role"
-   #
-   ## Follow the below instructions to use an API key and secret instead of keyless authentication.
-   ## In your GitLab environment, select the project you want to scan.
-   ## Go to `Settings` > `CI/CD`.
-   ## Click `Expand` in the `Variables` section.
-   ## Click the `Add variable` button at the bottom of the section. 
-   ## In the `Key` field, enter ENDOR_API_CREDENTIALS_SECRET.
-   ## In the `Value` field, enter your Endor Labs API secret.
-   ## Under `Flags` make sure you select `Mask variable`.
-   ## Repeat to add your API key as the variable ENDOR_API_CREDENTIALS_KEY
-   #
 Endor Labs Dependency Scan:
   stage: Scan
-  image: maven:3.6.3-jdk-11 # Modify this image to align with the build tools nessesary to build your software packages
+  image: node # Modify this image to align with the build tools nessesary to build your software packages
+  dependencies: []
+  variables:
+    ENDOR_ENABLED: "true"
+    ENDOR_ALLOW_FAILURE: "true"
+    ENDOR_NAMESPACE: "demo"
+    ENDOR_PROJECT_DIR: "."
+    GIT_DEPTH: 0
+    ENDOR_ARGS: |
+      --path=${ENDOR_PROJECT_DIR}
+      --detached-ref-name=$CI_COMMIT_REF_NAME
+      --output-type=summary
+      --dependencies --secrets --git-logs
   before_script:
-    # Install jq to download endorctl
-    - apt-get update && apt-get install -y jq
-    # Download and integrity check the endorctl binary
-    - if [ "$ENDORCTL_VERSION" == "latest" ]; then
-        echo "Downloading latest version of endorctl";
-        ENDORCTL_SHA=$(curl https://api.endorlabs.com/meta/version | jq -r '.ClientChecksums.ARCH_TYPE_LINUX_AMD64');
-        VERSION=$(curl https://api.endorlabs.com/meta/version | jq -r '.Service.Version');
-        curl https://storage.googleapis.com/endorlabs/"$VERSION"/binaries/endorctl_"$VERSION"_linux_amd64 -o endorctl;
-        echo "$ENDORCTL_SHA  endorctl" | sha256sum -c;
-        if [ $? -ne 0 ]; then 
-          echo "Integrity check failed"; 
-          exit 1;
-        fi
-      else
-        echo Downloading version "$ENDORCTL_VERSION" of endorctl;
-        curl https://storage.googleapis.com/endorlabs/"$ENDORCTL_VERSION"/binaries/endorctl_"$ENDORCTL_VERSION"_linux_amd64 -o endorctl;
-        echo "$ENDORCTL_SHA  endorctl" | sha256sum -c;
-        if [ $? -ne 0 ]; then 
-          echo "Integrity check failed for the pinned version of endorctl. Please ensure the environment variable is set and re-run the job"; 
-          exit 1;
-        fi
-      fi
-    - chmod +x ./endorctl
-    - mvn clean install # Replace with your packages build steps. 
+    - npm install package.json
   script:
+    - curl https://api.endorlabs.com/download/latest/endorctl_linux_amd64 -o endorctl;
+    - echo "$(curl -s https://api.endorlabs.com/sha/latest/endorctl_linux_amd64)  endorctl" | sha256sum -c;
+      if [ $? -ne 0 ]; then 
+       echo "Integrity check failed"; 
+       exit 1;
+      fi
     - if [ "$DEBUG" == "true" ]; then
         export ENDOR_LOG_VERBOSE=true;
         export ENDOR_LOG_LEVEL=debug;
@@ -75,4 +37,16 @@ Endor Labs Dependency Scan:
       else
         export ENDOR_SCAN_PR=true;
       fi
-    - ./endorctl scan --dependencies --secrets
+    - ./endorctl scan ${ENDOR_ARGS}
+  rules:
+  - if: $ENDOR_ENABLED != "true"
+    when: never
+  - if: $CI_COMMIT_TAG
+    when: never
+  - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH && $ENDOR_FEATURE_BRANCH_ENABLED != "true"
+    when: never
+  - if: $ENDOR_ALLOW_FAILURE == "true"
+    allow_failure: true
+  - if: $ENDOR_ALLOW_FAILURE != "true"
+    allow_failure: false
+
